### ISSUE TITLE
可以改成私信订阅B站么？

### ISSUE THREAD

**Issue by SecPhases** [snowtafir/xianxin-plugin#3]
在群里订阅有时候会错过。。不知道直接把message.group改成message可行么？或者添加一个提醒订阅人的功能？

**Comment by snowtafir** [comment]
> 在群里订阅有时候会错过。。不知道直接把message.group改成message可行么？或者添加一个提醒订阅人的功能？

仅仅修改这些还不够，还有多处需要调整的。。可以用小号弄个3人群单独订阅，或者如果使用频道的话，沙箱频道子频道设置仅管理员可见权限后同步订阅一下就行。。

**Comment by SecPhases** [comment]
> > 在群里订阅有时候会错过。。不知道直接把message.group改成message可行么？或者添加一个提醒订阅人的功能？
> 
> 仅仅修改这些还不够，还有多处需要调整的。。可以用小号弄个3人群单独订阅，或者如果使用频道的话，沙箱频道子频道设置仅管理员可见权限后同步订阅一下就行。。

明白了，感谢解答
